### ISSUE TITLE
NameError: name 'QtGui' is not defined

### ISSUE THREAD

**Issue by sebma** [inxi/guanxi#2]
Hi,

I'm using Ubuntu and I have the following error : 
```
$ ./gui.py 
Traceback (most recent call last):
  File "./gui.py", line 20, in <module>
    from inxiLib import buttonPanel, interface
  File "/home/sebastien/src/guanxi/inxiLib/__init__.py", line 1, in <module>
    from .buttonPanel import *
  File "/home/sebastien/src/guanxi/inxiLib/buttonPanel.py", line 4, in <module>
    from inxiWidgets import inxiWindow, inxiPopup
  File "/home/sebastien/src/guanxi/inxiWidgets/__init__.py", line 3, in <module>
    from .buttonPanel import *
  File "/home/sebastien/src/guanxi/inxiWidgets/buttonPanel.py", line 8, in <module>
    class ButtonPanel(QtGui.QGroupBox):
NameError: name 'QtGui' is not defined
```

Can you tell what is missing on my pc to make this work ?

**Comment by trash-80** [comment]
This project is quite old and I haven't worked on it in about 4 years.
